Change cloud tenants description to text
The 255 character limit on the cloud tenant description field causes inventory
collection to irreparably fail with the error:

PGError: ERROR:  value too long for type character varying(255)

Since OpenStack allows a tenant description value larger than 255 characters,
openstack inventory collection must support tenant descriptions larger than 255
characters.

https://bugzilla.redhat.com/show_bug.cgi?id=1263744

(transferred from ManageIQ/manageiq@dd3048b2bf88c988f081769507395c3c8d22d164)