[rails6] Require 'pp' for `.pretty_inspect`
Not sure if this comes from `Kernel.pretty_inspect`, or the gem of the
same name:

https://rubygems.org/gems/pretty_inspect/

Including this should get rid of the error that we are receiving in CI:

    ** Creating database with REGION 60

    rake aborted!
    StandardError: An error has occurred, this and all later migrations
    canceled:

    undefined method `pretty_inspect' for #<Hash:0x000000000430a418>
    ./lib/migration_helper.rb:102:in `block in rename_class_references'
    ./activerecord-6.0.3.4/lib/active_record/migration.rb:749:in `block in reversible'
    .activerecord-6.0.3.4/lib/active_record/migration.rb:977:in `execute_block'
    ...

https://travis-ci.com/github/ManageIQ/manageiq-cross_repo-tests/jobs/457650725#L494-L501